from sqlalchemy.orm import Session

from app.models.interaction import Interaction
from app.models.hcp import HCP
from app.services.ai_service import AIService


class InteractionAIService:

    @staticmethod
    def save_chat_interaction(
        db: Session,
        conversation: str
    ):

        ai = AIService.extract_interaction(conversation)

        interaction = Interaction(
            hcp_id=1,
            doctor_name=ai["doctor_name"],
            mode="Chat",
            discussion=conversation,
            products_discussed=", ".join(ai["products_discussed"]),
            sample_given="No",
            followup_date=ai["next_followup"],
            summary=ai["summary"],
            notes="Generated by AI",
            next_action=ai["next_followup"],
            sentiment=ai["sentiment"]
        )

        db.add(interaction)
        db.commit()
        db.refresh(interaction)

        return interaction